require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-md

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - '**/{tmp,templates,vendor}/**/*'
    - '**/{actionmailbox,activestorage,actiontext}/test/dummy/**/*'
    - 'tools/rail_inspector/test/fixtures/*'
    - guides/source/{debugging_rails_applications,active_support_instrumentation}.md
    - '**/{node_modules,CHANGELOG.md,2_*_release_notes.md,3_*_release_notes.md,4_*_release_notes.md,5_*_release_notes.md,6_*_release_notes.md}'

Performance:
  Exclude:
    - '**/test/**/*'

Rails/AssertNot:
  Include:
    - '**/test/**/*'

Rails/RefuteMethods:
  Include:
    - '**/test/**/*'

Rails/IndexBy, Rails/IndexWith, Style/AndOr:
  Enabled: true

Layout:
  ClosingHeredocIndentation: true
  ClosingParenthesisIndentation: true
  CommentIndentation: true
  DefEndAlignment: true
  ElseAlignment: true
  EndAlignment:
    EnforcedStyleAlignWith: variable
    AutoCorrect: true
  EndOfLine: true
  EmptyLineAfterMagicComment: true
  EmptyLinesAroundAccessModifier:
    EnforcedStyle: only_before
  EmptyLinesAroundBlockBody, EmptyLinesAroundClassBody, EmptyLinesAroundMethodBody, EmptyLinesAroundModuleBody: true
  IndentationConsistency:
    EnforcedStyle: indented_internal_methods
  IndentationWidth: true
  LeadingCommentSpace: true
  SpaceAroundKeyword, SpaceAroundOperators, SpaceBeforeBlockBraces, SpaceInsideBlockBraces: true

Style:
  HashSyntax:
    EnforcedShorthandSyntax: either
  DefWithParentheses, MethodDefParentheses: true
  FrozenStringLiteralComment:
    EnforcedStyle: always
    Exclude:
      - 'actionview/test/**/*.builder'
      - 'actionview/test/**/*.ruby'
      - '**/*.md'
  StringLiterals:
    EnforcedStyle: double_quotes
  RedundantFreeze: true
  RedundantReturn:
    AllowMultipleReturnValues: true

Lint:
  AmbiguousOperator, AmbiguousRegexpLiteral, Debugger, DuplicateRequire, DuplicateMagicComment, EnsureReturn, SafeNavigationChain: true
  RedundantCopDisableDirective, RedundantRequireStatement, UselessAssignment: true
